---
- name: Prepare test environment
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install test dependencies
      ansible.builtin.apt:
        name:
          - systemd
        state: present
        update_cache: true
