---
services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible_control
    privileged: true
    volumes:
      - .:/ansible
      - /var/run/docker.sock:/var/run/docker.sock
    command: tail -f /dev/null
