---
- name: Apply common configuration to all nodes
  hosts: all
  become: true
  roles:
    - common
    - docker

- name: Initialize Docker Swarm on manager node
  hosts: odin
  become: false
  roles:
    - docker-swarm-init
