---
- name: Apply common configuration to all nodes
  hosts: all
  become: true
  roles:
    - common
    - docker
    - python-requirements

- name: Initialize Docker Swarm on primary manager node
  hosts: odin
  become: false
  vars:
    ansible_python_interpreter: >-
      {{ ansible_venv_python_interpreter | default('/usr/bin/python3') }}
  roles:
    - docker-swarm-init

- name: Join additional managers to Docker Swarm
  hosts: managers:!odin
  become: false
  vars:
    swarm_manager_token: "{{ hostvars['odin']['manager_token'] }}"
    swarm_primary_manager_host: "{{ hostvars['odin']['ansible_host'] }}"
    ansible_python_interpreter: >-
      {{ ansible_venv_python_interpreter | default('/usr/bin/python3') }}
  tasks:
    - name: Include docker-swarm-manager role for additional managers
      ansible.builtin.include_role:
        name: docker-swarm-manager
      when: groups['managers'] | length > 1

- name: Join workers to Docker Swarm
  hosts: workers
  become: false
  vars:
    swarm_worker_token: "{{ hostvars['odin']['worker_token'] }}"
    swarm_primary_manager_host: "{{ hostvars['odin']['ansible_host'] }}"
    ansible_python_interpreter: >-
      {{ ansible_venv_python_interpreter | default('/usr/bin/python3') }}
  tasks:
    - name: Include docker-swarm-worker role for worker nodes
      ansible.builtin.include_role:
        name: docker-swarm-worker
      when: groups['workers'] | length > 0
