---
# roles/docker_manager/tasks/main.yml
# Docker Swarm Manager Configuration

- name: Check if Docker Swarm is already initialized
  ansible.builtin.command: >
    docker info --format "{{ '{{' }}.Swarm.LocalNodeState{{ '}}' }}"
  register: swarm_state
  changed_when: false
  failed_when: false

- name: Initialize Docker Swarm (if not already initialized)
  ansible.builtin.command: >
    docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
  when:
    - swarm_state.stdout != "active"
    - ansible_hostname == groups['managers'][0]
  register: swarm_init_result
  changed_when: swarm_init_result.rc == 0

- name: Get worker join token
  ansible.builtin.command: docker swarm join-token -q worker
  register: worker_token
  when: swarm_state.stdout == "active" or swarm_init_result is defined
  changed_when: false
