---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance-manager
    image: ubuntu:22.04
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    environment:
      container: docker
    published_ports:
      - "2377:2377"  # Docker Swarm management port

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
  playbooks:
    converge: converge.yml
    prepare: prepare.yml
  inventory:
    host_vars:
      instance-manager:
        ansible_user: root

verifier:
  name: testinfra
  directory: ./tests
  options:
    v: 1

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
