---
# Simple test for docker-swarm-worker role
- name: Test docker-swarm-worker role
  hosts: workers
  become: true
  gather_facts: true
  vars:
    # Mock variables that would normally come from the manager
    swarm_primary_manager_host: "172.17.0.2"
    swarm_worker_token: "SWMTKN-1-test-token"
    ansible_host: "{{ ansible_default_ipv4.address | default('172.17.0.3') }}"
  tasks:
    - name: Mock Docker installation
      ansible.builtin.debug:
        msg: "In a real scenario, Docker would be installed here"

    - name: Include docker-swarm-worker role
      ansible.builtin.include_role:
        name: docker-swarm-worker
