---
- name: Prepare test environment
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install Python if not present
      ansible.builtin.raw: |
        if ! command -v python3 &> /dev/null; then
          apt-get update && apt-get install -y python3 python3-pip
        fi
      changed_when: false

    - name: Gather facts after Python is available
      ansible.builtin.setup:

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-docker
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true

    - name: Install pip Docker SDK
      ansible.builtin.pip:
        name: docker
        state: present

- name: Install required Ansible collections
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install community.docker collection
      ansible.builtin.command: ansible-galaxy collection install community.docker
      changed_when: false