---
- name: Prepare test environment
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install required Python packages
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-docker
        state: present
        update_cache: true

    - name: Install pip Docker SDK
      ansible.builtin.pip:
        name: docker
        state: present