---
- name: Prepare test environment
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install Python if not present
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt-get update && apt-get install -y python3)
      changed_when: false

    - name: Install required Python packages
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-docker
        state: present
        update_cache: true

    - name: Ensure symlinks are available
      ansible.builtin.file:
        src: /usr/bin/python3
        dest: /usr/bin/python
        state: link
      failed_when: false

    - name: Gather facts after Python is available
      ansible.builtin.setup: