---
- name: Prepare test environment
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install test dependencies
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - python3-docker
          - curl
          - gnupg
          - ca-certificates
        state: present
        update_cache: true

    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: docker
        state: present
