---
- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Restart systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
