---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    docker_registry_username: testuser
    docker_registry_password: testpass
    docker_registry_url: docker.io
  tasks:
    - name: Include docker role
      ansible.builtin.include_role:
        name: docker
