---
- name: Prepare test environment
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install test dependencies
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - systemd
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true
