---
- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg
    mode: '0644'

- name: Convert and install Docker GPG key
  ansible.builtin.shell: |
    gpg --dearmor < /tmp/docker.gpg > /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ ansible_architecture | replace('x86_64', 'amd64') | replace('aarch64', 'arm64') }}
      signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
      https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: present
  notify: Restart docker
  when: not (molecule_test_environment | default(false))
  tags: [docker]

- name: Install Docker (test environment)
  ansible.builtin.apt:
    name: docker-ce
    state: present
  when: molecule_test_environment | default(false)
  tags: [docker]

- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Ensure Docker service is started and enabled
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  tags: [docker, services, molecule-notest]

- name: Configure NTP with systemd-timesyncd
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: '^#?NTP='
    line: 'NTP={{ common_ntp_server }}'
  notify: Restart systemd-timesyncd
  when: not (molecule_test_environment | default(false))

- name: Configure NTP with systemd-timesyncd (test environment)
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: '^#?NTP='
    line: 'NTP={{ common_ntp_server }}'
  when: molecule_test_environment | default(false)

- name: Ensure systemd-timesyncd service is started and enabled
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: started
    enabled: true
  tags: [timesyncd, services, molecule-notest]

- name: Log in to Docker registry
  community.docker.docker_login:
    username: "{{ docker_registry_username | default(omit) }}"
    password: "{{ docker_registry_password | default(omit) }}"
    registry_url: "{{ docker_registry_url | default('docker.io') }}"
  when: >-
    docker_registry_username is defined and
    docker_registry_password is defined
  tags: [docker, registry, molecule-notest]
