---
- name: Configure NTP with systemd-timesyncd
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: '^#?NTP='
    line: 'NTP={{ common_ntp_server }}'
  tags: [timesyncd]

- name: Restart systemd-timesyncd after configuration (production only)
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
  tags: [timesyncd, molecule-notest]

- name: Ensure systemd-timesyncd service is started and enabled
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: started
    enabled: true
  tags: [timesyncd, services, molecule-notest]
