---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache
      ansible.builtin.raw: apt-get update
      changed_when: false

    - name: Install Python and basic dependencies
      ansible.builtin.raw: >
        apt-get install -y python3 python3-pip systemd curl gnupg lsb-release
      changed_when: false

- name: Converge
  hosts: all
  gather_facts: true
  vars:
    common_ntp_server: 0.pool.ntp.org
    docker_registry_username: testuser
    docker_registry_password: testpass
    docker_registry_url: docker.io
  tasks:
    - name: Include common role
      include_role:
        name: common
