---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    common_ntp_server: 0.pool.ntp.org
  tasks:
    - name: Include common role
      ansible.builtin.include_role:
        name: common
