--- # Molecule Test Scenario for Common Role

# Define the platforms (OS/distribution) to test against
platforms:
  - name: instance
    # The tests will run directly on the ansible-control container

# Define the provisioner (Ansible in this case)
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

# Define the verifier (Testinfra in this case)
verifier:
  name: testinfra
  directory: ./tests

# Define the driver (Delegated in this case)
driver:
  name: delegated
  options:
    managed: false

# Define the scenario (default in this case)
scenario:
  name: default