---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:22.04
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: "sleep infinity"
    pre_build_image: false
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: root
        ansible_connection: docker
        ansible_python_interpreter: /usr/bin/python3
        # Variable to skip handlers that don't work in containers
        molecule_test_environment: true
  env:
    ANSIBLE_ROLES_PATH: ../../..
verifier:
  name: testinfra
