---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: python_requirements_role_instance
    image: ubuntu:22.04
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: "sleep infinity"
    pre_build_image: false
provisioner:
  name: ansible
  ansible_args:
    - --skip-tags
    - molecule-notest
  inventory:
    host_vars:
      python_requirements_role_instance:
        ansible_user: root
        ansible_connection: docker
        ansible_python_interpreter: /usr/bin/python3
  env:
    ANSIBLE_ROLES_PATH: ../../..
verifier:
  name: testinfra
